### ISSUE TITLE
Federating the Murmurations protocol

### ISSUE THREAD

**Issue by aschrijver** [MurmurationsNetwork/MurmurationsProtocol#30]
Some time ago at the SocialHub community I created a topic highlighting the opportunity to federate Murmurations using ActivityPub and bring the capabilities of Murmurations to the Fediverse, while removing the need for centralized index server.

Creating this issue to point to that, and as reference in other issues. See: [Federating the Murmurations protocol](https://socialhub.activitypub.rocks/t/federating-the-murmurations-protocol/1701).

(There's also an additional fediverse-related use case, namely [Improvement to FEDERATION.md convention: Murmurations protocol](https://socialhub.activitypub.rocks/t/improvement-to-federation-md-convention-murmurations/1573), and possibly one for [Delegated Moderation](https://socialhub.activitypub.rocks/t/federated-moderation-towards-delegated-moderation/1580) too)

**Comment by geoffturk** [comment]
Closing this issue since it does not relate to an issue to address/fix in the protocol. Feel free to discuss ideas like the above in our [GitHub Discussions forum](https://github.com/MurmurationsNetwork/MurmurationsProtocol/discussions). 👍
