### ISSUE TITLE
Compound Profiles

### ISSUE THREAD

**Issue by aschrijver** [MurmurationsNetwork/MurmurationsProtocol#31]
So Murmurations allow aggregation of predefined profiles. This issue is an idea to allow Compound Profiles: Multiple smaller profiles are aggregated into a larger compound profile that can be consumed by subscribers.

An example use case..

## Website Theme Directories

There are tons of static site generators, like Jekyll and Hugo and many others. They use Themes with which one can quickly publish a new website with the desired look & feel. As a result there are also numerous websites that collect and advertise themes. The theme collection is a manual process. Often the themes are ranked by popularity based on the number of Github stars they have. This works, but is a problem if a developer hosts their theme somewhere else than on Github.

A Compound Profile may offer a solution:

- Theme providers register a Theme Profile using murmations. Any theme aggregator site can consume these.
- Theme users host a Theme Usage Profile (which may already embedded in the theme).

The Theme Usage Profile is a child of the compound Theme Profile and its registration will update the `used_by` field in the parent, thereby providing the metric with which to measure popularity of the theme.

**Comment by geoffturk** [comment]
Closing this issue since it does not relate to an issue to address/fix in the protocol. Feel free to discuss ideas like the above in our [GitHub Discussions forum](https://github.com/MurmurationsNetwork/MurmurationsProtocol/discussions). 👍
