### ISSUE TITLE
Wordpress Plugin, US Country Code, Uploading File Instructions

### ISSUE THREAD

**Issue by Rmballesteros** [MurmurationsNetwork/MurmurationsProtocol#39]
Hey folks! Renata here. It's been a minute and I was glad to see the profile generator up still running nicely and the map looking good. I noticed that my profile was no longer appearing in the directory, so I decided to troubleshoot. It was really good to go through the process of creating a profile and interacting with the generator with fresh eyes, so it made me notice a few points that might need attention:

- **WordPress Plugin** I saw Murmurations listed on my plugins, but since it was not linking, I decided to delete it and start over.  A search for 'Murmurations' on the WordPress Plugin Index did not yield anything and I could not remember the process Oli described in Open 2020 for setting it up (if you still have the footage, it would be amazing to have the video embedded on the FAQ's section, or at least a link to it). Are there instructions on how to publish a json file on WP published somewhere I am missing? Is that still an option you are handling?

- **US ISO Country Code** Since the WordPress route didn't seem to work, I went back to the profile Generator and while filling out the form I noticed that the US code on the drop down for the ISO standard was missing

- **URI UX** I also had to spend a few minutes looking up with URI stood for and what the correct way to enter it was for the field. If this item is a must-have for the protocol to work correctly, then having a short explanation on the form of what it is and what format to enter it would be super helpful for user experience.

- **Self Hosting for Dummies** - On that vein, it would be really helpful to have a few steps outlined on how to publish the generated profile code on a site.

Thanks and let me know if I can help through this process, I'd be happy to volunteer some time into drafting instructions or whatevs. 

Cheers!

Renata

**Comment by geoffturk** [comment]
Great feedback. Thank you! We're ready to receive and start testing out ideas now so ping me when you have a chance. The Murmurations Protocol V2 is shaping up to be really nice. 🚀
